### List all messages

GET http://localhost:3001/messages

### Create a new message
POST http://localhost:3001/messages
content-type: application/json

{
  "content": "Hey!",
    "id": 13
}


### Get a particular message
GET http://localhost:3001/messages/120